"""HybridBlueprint model — result of fusing two blueprints."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

from core.blueprints.blueprint import Blueprint


@dataclass
class HybridBlueprint:
    """
    A blueprint generated by fusing two source blueprints.

    Contains the merged blueprint plus metadata about the fusion.
    """

    name: str = ""
    blueprint: Optional[Blueprint] = None
    source_a: str = ""
    source_b: str = ""
    fusion_ratio: float = 0.5
    fusion_method: str = "weighted"
    critic_score: float = 0.0
    playtest_score: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def is_valid(self) -> bool:
        return self.blueprint is not None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "blueprint": self.blueprint.to_dict() if self.blueprint else None,
            "source_a": self.source_a,
            "source_b": self.source_b,
            "fusion_ratio": self.fusion_ratio,
            "fusion_method": self.fusion_method,
            "critic_score": self.critic_score,
            "playtest_score": self.playtest_score,
            "metadata": self.metadata,
        }