-- OpenTibiaBR RME Map - Hito26_1B_Validation
-- Generated by RME Map AI Agent MVP V0.1
-- Tiles: 25 | Rooms: 0 | Spawns: 24

if not app.hasMap() then
    return
end

local map = app.map

app.transaction("Hito26_1B_Validation", function()
  -- Map dimensions: 5x5
  -- Base position: (1000, 1000, 7)

  -- Tile (0, 0, 7)
  local t = map:getOrCreateTile(0, 0, 7)
  t.ground = 106

  -- Tile (0, 1, 7)
  local t = map:getOrCreateTile(0, 1, 7)
  t.ground = 106

  -- Tile (0, 2, 7)
  local t = map:getOrCreateTile(0, 2, 7)
  t.ground = 106

  -- Tile (0, 3, 7)
  local t = map:getOrCreateTile(0, 3, 7)
  t.ground = 106

  -- Tile (0, 4, 7)
  local t = map:getOrCreateTile(0, 4, 7)
  t.ground = 106

  -- Tile (1, 0, 7)
  local t = map:getOrCreateTile(1, 0, 7)
  t.ground = 106

  -- Tile (1, 1, 7)
  local t = map:getOrCreateTile(1, 1, 7)
  t.ground = 106

  -- Tile (1, 2, 7)
  local t = map:getOrCreateTile(1, 2, 7)
  t.ground = 106

  -- Tile (1, 3, 7)
  local t = map:getOrCreateTile(1, 3, 7)
  t.ground = 106

  -- Tile (1, 4, 7)
  local t = map:getOrCreateTile(1, 4, 7)
  t.ground = 106

  -- Tile (2, 0, 7)
  local t = map:getOrCreateTile(2, 0, 7)
  t.ground = 106

  -- Tile (2, 1, 7)
  local t = map:getOrCreateTile(2, 1, 7)
  t.ground = 106

  -- Tile (2, 2, 7)
  local t = map:getOrCreateTile(2, 2, 7)
  t.ground = 106

  -- Tile (2, 3, 7)
  local t = map:getOrCreateTile(2, 3, 7)
  t.ground = 106

  -- Tile (2, 4, 7)
  local t = map:getOrCreateTile(2, 4, 7)
  t.ground = 106

  -- Tile (3, 0, 7)
  local t = map:getOrCreateTile(3, 0, 7)
  t.ground = 106

  -- Tile (3, 1, 7)
  local t = map:getOrCreateTile(3, 1, 7)
  t.ground = 106

  -- Tile (3, 2, 7)
  local t = map:getOrCreateTile(3, 2, 7)
  t.ground = 106

  -- Tile (3, 3, 7)
  local t = map:getOrCreateTile(3, 3, 7)
  t.ground = 106

  -- Tile (3, 4, 7)
  local t = map:getOrCreateTile(3, 4, 7)
  t.ground = 106

  -- Tile (4, 0, 7)
  local t = map:getOrCreateTile(4, 0, 7)
  t.ground = 106

  -- Tile (4, 1, 7)
  local t = map:getOrCreateTile(4, 1, 7)
  t.ground = 106

  -- Tile (4, 2, 7)
  local t = map:getOrCreateTile(4, 2, 7)
  t.ground = 106

  -- Tile (4, 3, 7)
  local t = map:getOrCreateTile(4, 3, 7)
  t.ground = 106

  -- Tile (4, 4, 7)
  local t = map:getOrCreateTile(4, 4, 7)
  t.ground = 106

  -- Spawn: Skeleton at (0, 0, 7)
  local s = map:getOrCreateTile(0, 0, 7)
  s:setSpawn(60)
  s:setCreature("Skeleton", 60, Direction.SOUTH)

  -- Spawn: Demon at (0, 1, 7)
  local s = map:getOrCreateTile(0, 1, 7)
  s:setSpawn(60)
  s:setCreature("Demon", 60, Direction.SOUTH)

  -- Spawn: Frazzlemaw at (0, 2, 7)
  local s = map:getOrCreateTile(0, 2, 7)
  s:setSpawn(60)
  s:setCreature("Frazzlemaw", 60, Direction.SOUTH)

  -- Spawn: Crypt Warden at (0, 3, 7)
  local s = map:getOrCreateTile(0, 3, 7)
  s:setSpawn(60)
  s:setCreature("Crypt Warden", 60, Direction.SOUTH)

  -- Spawn: Guzzlemaw at (0, 4, 7)
  local s = map:getOrCreateTile(0, 4, 7)
  s:setSpawn(60)
  s:setCreature("Guzzlemaw", 60, Direction.SOUTH)

  -- Spawn: Demon at (1, 0, 7)
  local s = map:getOrCreateTile(1, 0, 7)
  s:setSpawn(60)
  s:setCreature("Demon", 60, Direction.SOUTH)

  -- Spawn: Frazzlemaw at (1, 1, 7)
  local s = map:getOrCreateTile(1, 1, 7)
  s:setSpawn(60)
  s:setCreature("Frazzlemaw", 60, Direction.SOUTH)

  -- Spawn: Crypt Warden at (1, 2, 7)
  local s = map:getOrCreateTile(1, 2, 7)
  s:setSpawn(60)
  s:setCreature("Crypt Warden", 60, Direction.SOUTH)

  -- Spawn: Guzzlemaw at (1, 3, 7)
  local s = map:getOrCreateTile(1, 3, 7)
  s:setSpawn(60)
  s:setCreature("Guzzlemaw", 60, Direction.SOUTH)

  -- Spawn: Skeleton at (1, 4, 7)
  local s = map:getOrCreateTile(1, 4, 7)
  s:setSpawn(60)
  s:setCreature("Skeleton", 60, Direction.SOUTH)

  -- Spawn: Frazzlemaw at (2, 0, 7)
  local s = map:getOrCreateTile(2, 0, 7)
  s:setSpawn(60)
  s:setCreature("Frazzlemaw", 60, Direction.SOUTH)

  -- Spawn: Crypt Warden at (2, 1, 7)
  local s = map:getOrCreateTile(2, 1, 7)
  s:setSpawn(60)
  s:setCreature("Crypt Warden", 60, Direction.SOUTH)

  -- Spawn: Skeleton at (2, 3, 7)
  local s = map:getOrCreateTile(2, 3, 7)
  s:setSpawn(60)
  s:setCreature("Skeleton", 60, Direction.SOUTH)

  -- Spawn: Demon at (2, 4, 7)
  local s = map:getOrCreateTile(2, 4, 7)
  s:setSpawn(60)
  s:setCreature("Demon", 60, Direction.SOUTH)

  -- Spawn: Crypt Warden at (3, 0, 7)
  local s = map:getOrCreateTile(3, 0, 7)
  s:setSpawn(60)
  s:setCreature("Crypt Warden", 60, Direction.SOUTH)

  -- Spawn: Guzzlemaw at (3, 1, 7)
  local s = map:getOrCreateTile(3, 1, 7)
  s:setSpawn(60)
  s:setCreature("Guzzlemaw", 60, Direction.SOUTH)

  -- Spawn: Skeleton at (3, 2, 7)
  local s = map:getOrCreateTile(3, 2, 7)
  s:setSpawn(60)
  s:setCreature("Skeleton", 60, Direction.SOUTH)

  -- Spawn: Demon at (3, 3, 7)
  local s = map:getOrCreateTile(3, 3, 7)
  s:setSpawn(60)
  s:setCreature("Demon", 60, Direction.SOUTH)

  -- Spawn: Frazzlemaw at (3, 4, 7)
  local s = map:getOrCreateTile(3, 4, 7)
  s:setSpawn(60)
  s:setCreature("Frazzlemaw", 60, Direction.SOUTH)

  -- Spawn: Guzzlemaw at (4, 0, 7)
  local s = map:getOrCreateTile(4, 0, 7)
  s:setSpawn(60)
  s:setCreature("Guzzlemaw", 60, Direction.SOUTH)

  -- Spawn: Skeleton at (4, 1, 7)
  local s = map:getOrCreateTile(4, 1, 7)
  s:setSpawn(60)
  s:setCreature("Skeleton", 60, Direction.SOUTH)

  -- Spawn: Demon at (4, 2, 7)
  local s = map:getOrCreateTile(4, 2, 7)
  s:setSpawn(60)
  s:setCreature("Demon", 60, Direction.SOUTH)

  -- Spawn: Frazzlemaw at (4, 3, 7)
  local s = map:getOrCreateTile(4, 3, 7)
  s:setSpawn(60)
  s:setCreature("Frazzlemaw", 60, Direction.SOUTH)

  -- Spawn: Crypt Warden at (4, 4, 7)
  local s = map:getOrCreateTile(4, 4, 7)
  s:setSpawn(60)
  s:setCreature("Crypt Warden", 60, Direction.SOUTH)

  -- Boss: Orshabaal at (2, 2, 7)
  local b = map:getOrCreateTile(2, 2, 7)
  b:setSpawn(600)
  b:setCreature("Orshabaal", 600, Direction.SOUTH)

end)
