"""
Tests for Lua Exporter — WorldModel → Lua script pipeline.

Verifies that a WorldModel generated by the WorldGenerator can be
exported to a valid RME-compatible Lua script.
"""

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from core.generators import WorldGenerator, HuntGenerator
from core.exporters import LuaExporter, LuaValidator
from core.world import WorldModel, WorldValidator


def test_lua_exporter_basic():
    """Test basic export of a WorldModel to Lua."""
    # Generate a world
    generator = WorldGenerator(seed=42)
    world = generator.generate("Generate Issavi hunt level 300")

    # Export to Lua
    exporter = LuaExporter()
    lua_code = exporter.export(world)

    assert lua_code is not None
    assert len(lua_code) > 0
    assert "app.hasMap()" in lua_code
    assert "app.transaction" in lua_code
    assert "getOrCreateTile" in lua_code


def test_lua_exporter_has_ground():
    """Test that exported Lua sets ground tiles."""
    generator = WorldGenerator(seed=42)
    world = generator.generate("Generate Issavi hunt level 300")

    exporter = LuaExporter()
    lua_code = exporter.export(world)

    # Should contain tile.ground assignments
    assert "tile.ground =" in lua_code


def test_lua_exporter_has_spawns():
    """Test that exported Lua includes spawns if world has them."""
    hg = HuntGenerator(seed=42)
    world = hg.generate(WorldModel(), {
        "theme": "issavi",
        "level_min": 300,
        "level_max": 500,
        "density": "high",
    })

    exporter = LuaExporter()
    lua_code = exporter.export(world)

    # High density hunt should have some spawns
    has_spawn = "setSpawn" in lua_code or "setCreature" in lua_code
    assert has_spawn, "Expected setSpawn/setCreature in Lua output"


def test_lua_exporter_validator():
    """Test that exported Lua passes basic validation."""
    generator = WorldGenerator(seed=42)
    world = generator.generate("Generate Issavi hunt level 300")

    exporter = LuaExporter()
    result = exporter.validate(world)

    # Should pass (no forbidden APIs, balanced brackets)
    assert result.passed, f"Validation failed: {result.summary()}"


def test_lua_validator_empty():
    """Test validator rejects empty code."""
    validator = LuaValidator()
    result = validator.validate("")
    assert not result.passed
    assert len(result.errors) > 0


def test_lua_validator_forbidden_apis():
    """Test validator catches forbidden APIs."""
    validator = LuaValidator()

    bad_code = """
    if not app.hasMap() then return end
    app.transaction(function(map)
        tile:setGround(415)
    end)
    """
    result = validator.validate(bad_code)
    assert not result.passed
    assert any("forbidden" in e.lower() or "Forbidden" in e for e in result.errors)


def test_lua_validator_balanced():
    """Test validator catches unbalanced parentheses."""
    validator = LuaValidator()

    unbalanced = """
    if not app.hasMap() then return end
    app.transaction(function(map)
        -- missing closing paren
        local tile = map:getOrCreateTile(100, 100, 7
    end)
    """
    result = validator.validate(unbalanced)
    assert not result.passed
    assert any("unbalanced" in e.lower() or "Unbalanced" in e for e in result.errors)


def test_lua_writer_output():
    """Test LuaWriter produces correct output."""
    from core.exporters.lua_writer import LuaWriter

    writer = LuaWriter()
    writer.header("Test Zone")
    writer.transaction_begin()
    writer.set_ground(100, 100, 7, 415)
    writer.add_item(105, 105, 7, 1803)
    writer.set_spawn(110, 110, 7, "Sphinx", 60)
    writer.transaction_end()
    writer.end_statement()

    lua_code = writer.to_string()
    assert "Test Zone" in lua_code
    assert "app.hasMap()" in lua_code
    assert "app.transaction" in lua_code
    assert "map:getOrCreateTile(100, 100, 7)" in lua_code
    assert "tile.ground = 415" in lua_code
    assert "tile:addItem(1803)" in lua_code
    assert "setCreature('Sphinx'" in lua_code
    assert "setSpawn(60)" in lua_code


def test_lua_exporter_export_to_file(tmp_path):
    """Test exporting to a file."""
    generator = WorldGenerator(seed=42)
    world = generator.generate("Generate Issavi hunt level 300")

    exporter = LuaExporter()
    filepath = str(tmp_path / "test_hunt.lua")
    exporter.export_to_file(world, filepath)

    assert os.path.exists(filepath)
    with open(filepath, "r") as f:
        content = f.read()
    assert "app.hasMap()" in content


def test_full_pipeline():
    """Test the full pipeline: Prompt → WorldModel → Lua → Validation."""
    # Step 1: Generate world from prompt
    generator = WorldGenerator(seed=42)
    world = generator.generate("Generate Issavi hunt level 300")

    assert len(world.tiles) > 0
    assert world.region_count() == 1

    # Step 2: Validate WorldModel
    wv = WorldValidator()
    wv_result = wv.validate(world)
    assert wv_result.passed, f"World validation failed: {wv_result.summary()}"

    # Step 3: Export to Lua
    exporter = LuaExporter()
    lua_code = exporter.export(world, title="Full Pipeline Test")

    assert len(lua_code) > 0

    # Step 4: Validate Lua
    lv = LuaValidator()
    lv_result = lv.validate(lua_code)
    assert lv_result.passed, f"Lua validation failed: {lv_result.summary()}"

    # Step 5: Basic sanity checks on generated Lua
    assert "app.transaction(function(map)" in lua_code
    assert "map:getOrCreateTile" in lua_code
    assert "end)" in lua_code  # transaction close


if __name__ == "__main__":
    test_lua_exporter_basic()
    test_lua_exporter_has_ground()
    test_lua_exporter_has_spawns()
    test_lua_exporter_validator()
    test_lua_validator_empty()
    test_lua_validator_forbidden_apis()
    test_lua_validator_balanced()
    test_lua_writer_output()
    test_lua_exporter_export_to_file()
    test_full_pipeline()
    print("All lua_exporter tests passed!")