from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional


@dataclass
class DocumentationResult:
    """Result of documentation generation."""
    files_created: List[str] = field(default_factory=list)
    summary: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "files_created": self.files_created,
            "summary": self.summary,
        }


class DocumentationBuilder:
    """
    Generates project documentation automatically.

    Creates:
      - README.md        — Overview, install, usage
      - CHANGELOG.md     — Version history, changes added
      - MAP_GUIDE.md     — Zone guide, spawns, maps, difficulty
      - NPC_LIST.md      — All NPCs with positions
      - MONSTER_LIST.md  — All monsters with XP, loot, levels
      - SPAWN_TABLE.md   — Detailed spawn distribution
    """

    def __init__(self, output_dir: str | Path = "release/docs"):
        self.output_dir = Path(output_dir)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def build_all(self, map_data: Dict[str, Any], name: str = "expansion",
                  version: str = "1.0.0", author: str = "RME AI",
                  changelog_entries: Optional[List[str]] = None) -> DocumentationResult:
        """
        Generate all documentation files.

        Args:
            map_data: Dict with tiles, spawns, towns, etc.
            name: Base name of the expansion.
            version: Version string.
            author: Author name.
            changelog_entries: List of changes for CHANGELOG.md.

        Returns:
            DocumentationResult with paths to created files.
        """
        self.output_dir.mkdir(parents=True, exist_ok=True)
        created = []

        readme = self.build_readme(map_data, name, version, author)
        readme_path = self.output_dir / "README.md"
        readme_path.write_text(readme, encoding="utf-8")
        created.append(str(readme_path))

        changelog = self.build_changelog(version, changelog_entries)
        changelog_path = self.output_dir / "CHANGELOG.md"
        changelog_path.write_text(changelog, encoding="utf-8")
        created.append(str(changelog_path))

        guide = self.build_map_guide(map_data, name)
        guide_path = self.output_dir / "MAP_GUIDE.md"
        guide_path.write_text(guide, encoding="utf-8")
        created.append(str(guide_path))

        npcs = self.build_npc_list(map_data)
        npc_path = self.output_dir / "NPC_LIST.md"
        npc_path.write_text(npcs, encoding="utf-8")
        created.append(str(npc_path))

        monsters = self.build_monster_list(map_data)
        monster_path = self.output_dir / "MONSTER_LIST.md"
        monster_path.write_text(monsters, encoding="utf-8")
        created.append(str(monster_path))

        spawns = self.build_spawn_table(map_data)
        spawn_path = self.output_dir / "SPAWN_TABLE.md"
        spawn_path.write_text(spawns, encoding="utf-8")
        created.append(str(spawn_path))

        return DocumentationResult(
            files_created=created,
            summary=f"Generated {len(created)} documentation files for '{name}' v{version}",
        )

    def build_readme(self, map_data: Dict[str, Any], name: str,
                     version: str, author: str) -> str:
        """Generate README.md."""
        tiles = map_data.get("tiles", [])
        spawns = map_data.get("spawns", [])
        towns = map_data.get("towns", [])
        tile_count = len(tiles)
        spawn_count = len(spawns)
        town_count = len(towns)
        zone_count = len({s.get("name", "") for s in spawns})

        return f"""# {name.title()} — RME Expansion

**Version:** {version}
**Author:** {author}
**Generated by:** RME AI World Generator

## Overview

{tile_count} tiles | {spawn_count} spawns | {town_count} towns | {zone_count} zones

A procedurally generated Tibia map expansion created by the RME (Recursive Map Engine).

## Contents

- `{name}.otbm` — Main map file
- `{name}.lua` — Lua scripts (if applicable)
- `monster.xml` — Monster spawn configuration
- `npc.xml` — NPC definitions
- `zones.xml` — Zone metadata
- `MAP_GUIDE.md` — Complete zone guide
- `SPAWN_TABLE.md` — Detailed spawn distribution
- `MONSTER_LIST.md` — Monster stats and loot
- `NPC_LIST.md` — NPC locations
- `CHANGELOG.md` — Version history

## Installation

1. Copy `{name}.otbm` to your server's `data/world/` directory
2. Import `monster.xml` via RME or server console
3. Import `npc.xml` for NPC placement
4. Restart server or reload map

## Requirements

- Tibia client 12.x+ or compatible OTClient
- Server supporting OTBM format v4
- RME (Remere's Map Editor) for editing

## Map Features

- Balanced hunt zones with progressive difficulty
- Themed areas with coherent visual design
- Proper spawn distribution for solo and party play
- Connected road network and waypoints
- PZ zones in safe areas
"""

    def build_changelog(self, version: str,
                        entries: Optional[List[str]] = None) -> str:
        """Generate CHANGELOG.md."""
        if entries is None:
            entries = [
                "Initial release",
                "Map generation with RME AI",
                "Balanced spawn distribution",
                "Zone navigation and waypoints",
            ]

        lines = ["# Changelog", ""]
        lines.append(f"## v{version}")
        for entry in entries:
            lines.append(f"- {entry}")
        lines.append("")
        lines.append("---")
        lines.append("*Generated automatically by RME Documentation Builder*")
        return "\n".join(lines)

    def build_map_guide(self, map_data: Dict[str, Any], name: str) -> str:
        """Generate MAP_GUIDE.md with zone descriptions."""
        tiles = map_data.get("tiles", [])
        spawns = map_data.get("spawns", [])
        towns = map_data.get("towns", [])

        lines = [f"# {name.title()} — Map Guide", ""]
        lines.append("## Overview")
        lines.append(f"This map contains {len(spawns)} spawn zones across {len(towns)} towns.")
        lines.append("")

        # Town section
        if towns:
            lines.append("## Towns & Safe Zones")
            lines.append("")
            for town in towns:
                tname = town.get("name", "Unknown")
                tpos = town.get("position", (0, 0, 7))
                temple = town.get("temple_position", "N/A")
                lines.append(f"### {tname}")
                lines.append(f"- Position: ({tpos[0]}, {tpos[1]}, {tpos[2] if len(tpos) > 2 else 7})")
                lines.append(f"- Temple: {temple}")
                lines.append("")

        # Zones section
        if spawns:
            lines.append("## Hunt Zones")
            lines.append("")
            seen_zones: set = set()
            for spawn in spawns:
                zname = spawn.get("name", "Unknown Zone")
                if zname in seen_zones:
                    continue
                seen_zones.add(zname)
                pos = spawn.get("center_position", (0, 0, 7))
                radius = spawn.get("radius", 8)
                monsters = spawn.get("monsters", [])

                lines.append(f"### {zname}")
                lines.append(f"- Center: ({pos[0]}, {pos[1]}, {pos[2] if len(pos) > 2 else 7})")
                lines.append(f"- Radius: {radius} tiles")
                if monsters:
                    lines.append(f"- Monsters: {', '.join(m.get('name', '?') for m in monsters[:5])}")
                lines.append("")

        lines.append("## Navigation Tips")
        lines.append("- Use waypoints for auto-walk routes")
        lines.append("- Roads connect all major zones")
        lines.append("- Follow paths from towns to hunt areas")
        lines.append("- Boss rooms are marked at zone entrances")
        lines.append("")
        lines.append("---")
        lines.append("*Generated automatically by RME Documentation Builder*")
        return "\n".join(lines)

    def build_npc_list(self, map_data: Dict[str, Any]) -> str:
        """Generate NPC_LIST.md."""
        towns = map_data.get("towns", [])

        lines = ["# NPC List", ""]
        lines.append("| NPC | Town | Position | Type |")
        lines.append("|-----|------|----------|------|")

        if towns:
            for town in towns:
                tname = town.get("name", "Unknown")
                tpos = town.get("position", (0, 0, 7))
                pos_str = f"({tpos[0]}, {tpos[1]})"
                lines.append(f"| Temple NPC | {tname} | {pos_str} | Teleport/Rez |")
        else:
            lines.append("| _No towns defined_ | — | — | — |")

        lines.append("")
        lines.append("---")
        lines.append("*Generated automatically by RME Documentation Builder*")
        return "\n".join(lines)

    def build_monster_list(self, map_data: Dict[str, Any]) -> str:
        """Generate MONSTER_LIST.md."""
        spawns = map_data.get("spawns", [])

        monster_counts: Dict[str, int] = {}
        monster_zones: Dict[str, set] = {}

        for spawn in spawns:
            zname = spawn.get("name", "Unknown")
            for m in spawn.get("monsters", []):
                mname = m.get("name", "Unknown")
                monster_counts[mname] = monster_counts.get(mname, 0) + m.get("count", 1)
                if mname not in monster_zones:
                    monster_zones[mname] = set()
                monster_zones[mname].add(zname)

        lines = ["# Monster List", ""]
        if monster_counts:
            lines.append("| Monster | Count | Zones |")
            lines.append("|---------|-------|-------|")
            for mname in sorted(monster_counts.keys()):
                zones_str = ", ".join(monster_zones.get(mname, []))
                lines.append(f"| {mname} | {monster_counts[mname]} | {zones_str} |")
        else:
            lines.append("_No monsters defined_")

        lines.append("")
        lines.append("---")
        lines.append("*Generated automatically by RME Documentation Builder*")
        return "\n".join(lines)

    def build_spawn_table(self, map_data: Dict[str, Any]) -> str:
        """Generate SPAWN_TABLE.md with detailed spawn distribution."""
        spawns = map_data.get("spawns", [])

        lines = ["# Spawn Table", ""]
        lines.append("## Distribution by Zone")
        lines.append("")
        lines.append("| Zone | Center | Radius | Monsters | Raw Count |")
        lines.append("|------|--------|--------|----------|-----------|")

        for spawn in spawns:
            zname = spawn.get("name", "Unknown")
            pos = spawn.get("center_position", (0, 0, 7))
            radius = spawn.get("radius", 8)
            monsters = spawn.get("monsters", [])
            pos_str = f"({pos[0]}, {pos[1]}, {pos[2] if len(pos) > 2 else 7})"

            mstr = "; ".join(f"{m.get('name', '?')}x{m.get('count', 1)}" for m in monsters)
            raw_count = sum(m.get("count", 1) for m in monsters)

            lines.append(f"| {zname} | {pos_str} | {radius} | {mstr} | {raw_count} |")

        lines.append("")
        lines.append("---")
        lines.append("*Generated automatically by RME Documentation Builder*")
        return "\n".join(lines)