"""Read-only world.otbm validation for PMX-01A evidence reports."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def validate_world_otbm(
    workspace_root: str | Path | None = None,
    *,
    max_nodes: int = 12000,
    reports_root: str | Path | None = None,
) -> dict[str, Any]:
    root = Path(workspace_root or ".").resolve()
    world_path = root / "projects" / "world" / "world.otbm"
    out_root = Path(reports_root or root / "reports" / "WORLD")
    out_root.mkdir(parents=True, exist_ok=True)
    log_lines = [
        f"timestamp={datetime.now(timezone.utc).replace(microsecond=0).isoformat()}",
        f"world_path={world_path}",
        "mode=read-only",
    ]
    try:
        from core.opentibia.reference_learning import ReferenceWorldAnalyzer

        profile = ReferenceWorldAnalyzer(world_path, max_nodes=max_nodes).analyze().to_dict()
        state = "WORLD_OTBM_PARTIALLY_LOADED" if profile.get("parse_truncated") else "WORLD_OTBM_FULLY_LOADED"
        payload = {
            "state": state,
            "world_path": str(world_path),
            "read_only": True,
            "exported": False,
            "modified": False,
            "copied_areas": False,
            "profile": profile,
        }
        log_lines.append(f"state={state}")
        log_lines.append(f"sampled_tiles={profile.get('sampled_tile_count')}")
    except Exception as exc:
        payload = {
            "state": "WORLD_OTBM_LOAD_BLOCKED",
            "world_path": str(world_path),
            "read_only": True,
            "exported": False,
            "modified": False,
            "copied_areas": False,
            "error": f"{type(exc).__name__}: {exc}",
        }
        log_lines.append("state=WORLD_OTBM_LOAD_BLOCKED")
        log_lines.append(f"error={payload['error']}")

    (out_root / "world_otbm_load_validation.json").write_text(
        json.dumps(payload, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    (out_root / "world_otbm_load_validation.log").write_text("\n".join(log_lines) + "\n", encoding="utf-8")
    (out_root / "world_otbm_load_validation.md").write_text(
        "\n".join(
            [
                "# world.otbm Load Validation",
                "",
                f"- State: {payload['state']}",
                f"- Path: {payload['world_path']}",
                "- Mode: read-only",
                "- Modified: false",
                "- Exported: false",
                "- Copied areas: false",
                "- Evidence: JSON and log generated by `validate_world_otbm`.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    return payload
