"""
Playtest Engine — Automated playtesting for worlds generated by Agente RME.
"""

# --- Existing playtest modules ---
from .player_bot import PlayerBot, Vocation, VocationStats
from .party_bot import PartyBot, PartyRole
from .route_simulator import RouteSimulator, RouteMetrics, RouteResult

# --- New playtest engine modules ---
from .combat_simulator import CombatSimulator, CombatResult, CombatMode, MonsterStats
from .loot_simulator import LootSimulator, LootTable, LootDrop
from .pathfinder import Pathfinder, PathResult
from .progression_analyzer import ProgressionAnalyzer, ProgressionReport
from .difficulty_evaluator import DifficultyEvaluator, DifficultyReport
from .survival_analyzer import SurvivalAnalyzer, SurvivalReport
from .report_generator import ReportGenerator
from .playtest_engine import PlaytestEngine, PlaytestReport

__all__ = [
    "PlayerBot", "Vocation", "VocationStats",
    "PartyBot", "PartyRole",
    "RouteSimulator", "RouteMetrics", "RouteResult",
    "CombatSimulator", "CombatResult", "CombatMode", "MonsterStats",
    "LootSimulator", "LootTable", "LootDrop",
    "Pathfinder", "PathResult",
    "ProgressionAnalyzer", "ProgressionReport",
    "DifficultyEvaluator", "DifficultyReport",
    "SurvivalAnalyzer", "SurvivalReport",
    "ReportGenerator",
    "PlaytestEngine", "PlaytestReport",
]