"""
Exporter Audit — Analysis of current Agente RME OTBM exporter.

This module implements PHASE OTBM-RME-1B: Exporter Audit.

It audits the current Agente RME OTBM exporter to identify:
- Missing nodes
- Invalid nodes
- Hierarchy violations
- Serialization mismatches
"""

from dataclasses import dataclass
from typing import Dict, List

from .otbm_node_rules import NodeValidationRules
from .rme_compatibility_validator import RMECompatibilityValidator
from .validation_report import (
    SeverityLevel,
    ValidationIssue,
    ValidationReport,
    ValidationStatus,
)
from ..otbm_exporter import OTBMExporter
from .otbm_constants import (
    AGENTE_OTBM_NODE_HOUSETILE as AGENTE_HOUSETILE,
    AGENTE_OTBM_NODE_ITEM as AGENTE_ITEM,
    AGENTE_OTBM_NODE_MAP_DATA as AGENTE_MAP_DATA,
    AGENTE_OTBM_NODE_MONSTER as AGENTE_MONSTER,
    AGENTE_OTBM_NODE_ROOT as AGENTE_ROOT,
    AGENTE_OTBM_NODE_SPAWN_AREA as AGENTE_SPAWN_AREA,
    AGENTE_OTBM_NODE_SPAWNS as AGENTE_SPAWNS,
    AGENTE_OTBM_NODE_TILE as AGENTE_TILE,
    AGENTE_OTBM_NODE_TILE_AREA as AGENTE_TILE_AREA,
    AGENTE_OTBM_NODE_TOWN as AGENTE_TOWN,
    AGENTE_OTBM_NODE_TOWNS as AGENTE_TOWNS,
    AGENTE_OTBM_NODE_WAYPOINT as AGENTE_WAYPOINT,
    AGENTE_OTBM_NODE_WAYPOINTS as AGENTE_WAYPOINTS,
    OTBM_HOUSETILE,
    OTBM_ITEM,
    OTBM_MAP_DATA,
    OTBM_MONSTER,
    OTBM_ROOTV1,
    OTBM_SPAWN_AREA,
    OTBM_SPAWNS,
    OTBM_TILE,
    OTBM_TILE_AREA,
    OTBM_TOWN,
    OTBM_TOWNS,
    OTBM_WAYPOINT,
    OTBM_WAYPOINTS,
)


@dataclass
class ExporterAuditReport:
    """Structured report of exporter audit findings."""

    node_constant_mapping: Dict[str, Dict[str, int]]
    hierarchy_violations: List[str]
    missing_nodes: List[str]
    invalid_nodes: List[str]
    serialization_issues: List[str]
    recommendations: List[str]
    root_cause_analysis: str

    def to_dict(self) -> Dict:
        """Convert report to dictionary."""
        return {
            "node_constant_mapping": self.node_constant_mapping,
            "hierarchy_violations": self.hierarchy_violations,
            "missing_nodes": self.missing_nodes,
            "invalid_nodes": self.invalid_nodes,
            "serialization_issues": self.serialization_issues,
            "recommendations": self.recommendations,
            "root_cause_analysis": self.root_cause_analysis,
        }


class ExporterAudit:
    """
    Audits the current Agente RME OTBM exporter for Canary/RME compatibility.

    This class identifies the specific issues that cause OTBM files
    generated by Agente RME to fail in Remere's Map Editor.
    """

    def __init__(self):
        self.node_rules = NodeValidationRules()
        self.agente_constants = self._get_agente_constants()
        self.canary_constants = self._get_canary_constants()

    def _get_agente_constants(self) -> Dict[str, int]:
        """Get Agente RME node constants."""
        return {
            "ROOT": AGENTE_ROOT,
            "MAP_DATA": AGENTE_MAP_DATA,
            "TILE_AREA": AGENTE_TILE_AREA,
            "TILE": AGENTE_TILE,
            "ITEM": AGENTE_ITEM,
            "SPAWNS": AGENTE_SPAWNS,
            "SPAWN_AREA": AGENTE_SPAWN_AREA,
            "MONSTER": AGENTE_MONSTER,
            "TOWNS": AGENTE_TOWNS,
            "TOWN": AGENTE_TOWN,
            "HOUSETILE": AGENTE_HOUSETILE,
            "WAYPOINTS": AGENTE_WAYPOINTS,
            "WAYPOINT": AGENTE_WAYPOINT,
        }

    def _get_canary_constants(self) -> Dict[str, int]:
        """Get Canary/RME node constants."""
        return {
            "ROOT": OTBM_ROOTV1,
            "MAP_DATA": OTBM_MAP_DATA,
            "TILE_AREA": OTBM_TILE_AREA,
            "TILE": OTBM_TILE,
            "ITEM": OTBM_ITEM,
            "SPAWNS": OTBM_SPAWNS,
            "SPAWN_AREA": OTBM_SPAWN_AREA,
            "MONSTER": OTBM_MONSTER,
            "TOWNS": OTBM_TOWNS,
            "TOWN": OTBM_TOWN,
            "HOUSETILE": OTBM_HOUSETILE,
            "WAYPOINTS": OTBM_WAYPOINTS,
            "WAYPOINT": OTBM_WAYPOINT,
        }

    def perform_full_audit(self) -> ExporterAuditReport:
        """Perform comprehensive audit of the exporter."""
        return ExporterAuditReport(
            node_constant_mapping=self._analyze_node_constants(),
            hierarchy_violations=self._identify_hierarchy_violations(),
            missing_nodes=self._identify_missing_nodes(),
            invalid_nodes=self._identify_invalid_nodes(),
            serialization_issues=self._identify_serialization_issues(),
            recommendations=self._generate_recommendations(),
            root_cause_analysis=self._provide_root_cause_analysis(),
        )

    def _analyze_node_constants(self) -> Dict[str, Dict[str, int]]:
        """Analyze node constant discrepancies."""
        mapping = {}

        for node_name in self.agente_constants:
            agente_val = self.agente_constants[node_name]
            canary_val = self.canary_constants[node_name]

            mapping[node_name] = {
                "agente": agente_val,
                "canary": canary_val,
                "offset": canary_val - agente_val,
                "matches": agente_val == canary_val,
            }

        return mapping

    def _identify_hierarchy_violations(self) -> List[str]:
        """Identify potential hierarchy violations."""
        violations = []

        # Check if Agente exporter might create invalid hierarchies
        violations.append(
            "POTENTIAL_HIERARCHY_VIOLATION: Agente exporter may not enforce Canary hierarchy rules"
        )
        violations.append(
            "PARENT_CHILD_MISMATCH: Node constant offset could cause hierarchy validation failures"
        )
        violations.append(
            "ORDERING_ISSUES: Agente exporter may not respect Canary node ordering requirements"
        )

        return violations

    def _identify_missing_nodes(self) -> List[str]:
        """Identify missing nodes that should be present."""
        missing = []

        # Check if all required nodes are implemented
        required_nodes = ["ROOT", "MAP_DATA", "TILE_AREA", "TILE", "ITEM"]
        for node_name in required_nodes:
            if node_name not in self.agente_constants:
                missing.append(f"MISSING_NODE: {node_name} not found in Agente exporter")

        return missing

    def _identify_invalid_nodes(self) -> List[str]:
        """Identify nodes that might be invalid for RME."""
        invalid = []

        # Check for nodes that might cause issues
        invalid.append(
            "INVALID_NODE_CONSTANTS: All Agente node constants are offset by +1 from Canary"
        )
        invalid.append("ROOT_NODE_MISMATCH: Agente uses 0x00, Canary expects 0x01")
        invalid.append("MAP_DATA_MISMATCH: Agente uses 0x01, Canary expects 0x02")

        return invalid

    def _identify_serialization_issues(self) -> List[str]:
        """Identify potential serialization issues."""
        issues = []

        issues.append("SERIALIZATION_MISMATCH: Node type byte mismatch causes parsing failures")
        issues.append(
            "HIERARCHY_PARSING: RME misinterprets node relationships due to constant offset"
        )
        issues.append(
            "ATTRIBUTE_MISALIGNMENT: Attribute parsing may be affected by node type mismatch"
        )

        return issues

    def _generate_recommendations(self) -> List[str]:
        """Generate recommendations for fixing compatibility issues."""
        recommendations = []

        recommendations.append(
            "RECOMMENDATION: Align Agente node constants with Canary specification"
        )
        recommendations.append("RECOMMENDATION: Implement node constant conversion layer")
        recommendations.append("RECOMMENDATION: Add strict hierarchy validation to exporter")
        recommendations.append("RECOMMENDATION: Enforce Canary node ordering in output")
        recommendations.append(
            "RECOMMENDATION: Add compatibility validation step to export pipeline"
        )
        recommendations.append("RECOMMENDATION: Implement roundtrip testing for exported files")

        return recommendations

    def _provide_root_cause_analysis(self) -> str:
        """Provide detailed root cause analysis."""
        return """
ROOT CAUSE ANALYSIS: issavi_roshamuul_v1.otbm RME Node Errors

Primary Issue:
The fundamental incompatibility between Agente RME and Canary/RME is caused by
a systematic offset in node type constants:

Agente RME Constants (0x00-based):
- ROOT:      0x00
- MAP_DATA:  0x01
- TILE_AREA: 0x02
- TILE:      0x03
- ITEM:      0x04

Canary/RME Constants (0x01-based):
- ROOT:      0x01
- MAP_DATA:  0x02
- TILE_AREA: 0x04
- TILE:      0x05
- ITEM:      0x06

Impact Analysis:
1. When RME reads an Agente-generated OTBM file, it sees ROOT=0x00
2. RME expects ROOT=0x01, so it misinterprets the entire node tree
3. All subsequent nodes are parsed with wrong types, causing hierarchy errors
4. The file is rejected as having invalid node structure

Technical Details:
- Node type byte determines how RME parses each node
- +1 offset means every Agente node is interpreted as wrong type
- This cascades through the entire file structure
- Results in "node errors" and file rejection

Solution Requirements:
1. Convert Agente node constants to Canary format during export
2. Implement validation to ensure output matches Canary expectations
3. Add compatibility layer to handle both constant systems
4. Test roundtrip compatibility with actual RME instances
"""

    def audit_exporter_output(self, exporter: OTBMExporter, sample_data: bytes) -> ValidationReport:
        """Audit the actual output of the exporter."""
        report = ValidationReport(ValidationStatus.UNKNOWN)
        report.file_path = "Exporter Output Audit"

        # Validate the output against Canary requirements
        validator = RMECompatibilityValidator()
        validation_report = validator.validate(sample_data)

        # Copy issues from validation
        for issue in validation_report.issues:
            report.add_issue(issue)

        # Add exporter-specific issues
        report.add_issue(
            ValidationIssue(
                code="EXPORTER_AUDIT",
                message="Exporter output audit completed",
                severity=SeverityLevel.INFO,
                context="exporter_audit",
            )
        )

        # Update status
        if validation_report.has_critical_issues():
            report.status = ValidationStatus.FAILURE
        elif validation_report.has_errors():
            report.status = ValidationStatus.FAILURE
        elif len(report.issues) > 0:
            report.status = ValidationStatus.WARNING
        else:
            report.status = ValidationStatus.SUCCESS

        return report

    def generate_exporter_fix_report(self) -> str:
        """Generate a report on how to fix the exporter."""
        return """
EXPORTER FIX REPORT: Steps to Achieve RME Compatibility

1. NODE CONSTANT CONVERSION
   - Modify node_encoder.py to use Canary node constants
   - Add AGENTE_TO_CANARY_NODE_MAP for backward compatibility
   - Update all node encoding functions to use correct constants

2. HIERARCHY VALIDATION
   - Integrate NodeValidationRules into export pipeline
   - Add pre-export validation step
   - Reject invalid hierarchies before serialization

3. COMPATIBILITY LAYER
   - Create OTBM compatibility adapter
   - Support both Agente and Canary formats
   - Add format detection and conversion

4. EXPORT PIPELINE UPDATES
   - Add Canary validation step after serialization
   - Implement roundtrip testing
   - Add compatibility warnings and errors

5. TESTING INFRASTRUCTURE
   - Create Canary-compatible test OTBM files
   - Implement RME integration testing
   - Add regression test suite

6. DOCUMENTATION
   - Document compatibility requirements
   - Provide migration guide for existing maps
   - Update API documentation with compatibility notes

Estimated Implementation Time: 2-3 weeks
Priority: CRITICAL (blocks world.7z ingestion)
Impact: HIGH (affects all OTBM export functionality)
"""


__all__ = [
    "ExporterAudit",
    "ExporterAuditReport",
]
