"""
RME Compatibility Validator — OTBM validation against Canary/RME requirements.

This module implements PHASE OTBM-RME-1C: Compatibility Validator.

It provides comprehensive validation of OTBM files to ensure they meet
the exact requirements of Remere's Map Editor as documented in the
Canary Map Editor source code.
"""

import struct
import time
from typing import Dict, List, Optional, Tuple, cast
from dataclasses import dataclass, field
from .otbm_constants import (
    AGENTE_OTBM_NODE_ROOT,
    OTBM_ATTR_TILE_FLAGS,
    OTBM_HOUSETILE,
    OTBM_ACCEPTED_IDENTIFIERS,
    OTBM_IDENTIFIER,
    OTBM_ITEM,
    OTBM_MAP_DATA,
    OTBM_MONSTER,
    OTBM_ROOTV1,
    OTBM_SPAWN_AREA,
    OTBM_TILE,
    OTBM_TILE_AREA,
    OTBM_TOWN,
    OTBM_WAYPOINT,
)
from .otbm_node_rules import NodeValidationRules, ValidationResult
from .validation_report import (
    SeverityLevel,
    ValidationIssue,
    ValidationReport,
    ValidationStatistics,
    ValidationStatus,
)


@dataclass
class RMEValidationContext:
    """Context for RME validation operations."""

    file_path: Optional[str] = None
    file_size: int = 0
    validation_start_time: float = 0.0
    statistics: ValidationStatistics = field(default_factory=ValidationStatistics)
    issues: List[ValidationIssue] = field(default_factory=list)
    node_stack: List[int] = field(default_factory=list)
    current_depth: int = 0
    max_depth: int = 0


class RMECompatibilityValidator:
    """
    Validates OTBM files for compatibility with Remere's Map Editor.

    This validator implements strict validation rules based on the
    Canary Map Editor source code analysis, ensuring that OTBM files
    generated by Agente RME will be accepted by RME.
    """

    def __init__(self):
        self.node_rules = NodeValidationRules()
        self.context = RMEValidationContext()

    def validate(self, data: bytes, file_path: Optional[str] = None) -> ValidationReport:
        """Validate OTBM data for RME compatibility."""
        started = time.time()
        report = ValidationReport(ValidationStatus.UNKNOWN)
        report.file_path = file_path
        report.statistics.file_size = len(data)
        try:
            from ..otbm_importer import OTBMNodeReader

            with OTBMNodeReader(data) as reader:
                index = reader.build_index(max_nodes=None, max_bytes=None)
        except Exception as exc:  # noqa: BLE001 - compatibility gate fails closed
            report.add_issue(
                ValidationIssue(
                    code="HIERARCHY_CANARY_RME_TREE",
                    message=f"Invalid Canary/RME delimiter tree: {exc}",
                    severity=SeverityLevel.CRITICAL,
                    context="hierarchy",
                )
            )
            report.status = ValidationStatus.FAILURE
            report.validation_duration_ms = (time.time() - started) * 1000
            return report

        counts = index.stats.node_counts
        report.statistics = ValidationStatistics(
            total_nodes=index.stats.nodes_visited,
            tiles=index.stats.estimated_tiles,
            items=counts.get("ITEM", 0),
            spawn_areas=counts.get("SPAWN_AREA", 0),
            monsters=counts.get("MONSTER", 0),
            towns=counts.get("TOWN", 0),
            waypoints=counts.get("WAYPOINT", 0),
            house_tiles=counts.get("HOUSETILE", 0),
            file_size=len(data),
            version=index.metadata.get("version"),
            width=index.metadata.get("width"),
            height=index.metadata.get("height"),
            item_version=(
                f"{index.metadata.get('item_major_version', 0)}."
                f"{index.metadata.get('item_minor_version', 0)}"
            ),
        )
        report.status = ValidationStatus.SUCCESS
        report.canary_compatible = True
        report.rme_compatible = True
        report.validation_duration_ms = (time.time() - started) * 1000
        return report

    def _validate_legacy_size_prefixed_stream(
        self, data: bytes, file_path: Optional[str] = None
    ) -> ValidationReport:
        self._initialize_validation_context(file_path, data)

        report = ValidationReport(ValidationStatus.UNKNOWN)
        report.file_path = file_path
        report.file_path = file_path
        report.statistics.file_size = len(data)

        # Validate header first
        header_result = self._validate_header(data)
        if not header_result.passed:
            report.add_issue(self._create_issue_from_result(header_result, SeverityLevel.CRITICAL))
            report.status = ValidationStatus.FAILURE
            report.validation_duration_ms = self._get_validation_duration()
            return report

        # Parse and validate the entire node structure
        try:
            offset = 5  # Skip "OTBM" + root node type
            children_offset, _root_attrs = self._parse_root_node(data, offset)
            self._validate_full_structure(data, children_offset)
        except Exception as e:
            report.add_issue(
                ValidationIssue(
                    code="VALIDATION_ERROR",
                    message=f"Validation error: {str(e)}",
                    severity=SeverityLevel.CRITICAL,
                    context="structure_validation",
                )
            )
            report.status = ValidationStatus.FAILURE

        # Update report based on findings
        self._update_report_from_context(report)
        report.validation_duration_ms = self._get_validation_duration()

        return report

    def _initialize_validation_context(self, file_path: Optional[str], data: bytes):
        """Initialize validation context."""
        self.context = RMEValidationContext(
            file_path=file_path, file_size=len(data), validation_start_time=time.time()
        )

    def _get_validation_duration(self) -> float:
        """Get validation duration in milliseconds."""
        return cast(float, (time.time() - self.context.validation_start_time) * 1000)

    def _validate_header(self, data: bytes) -> ValidationResult:
        """Validate OTBM file header."""
        if len(data) < 5:
            return ValidationResult(False, "OTBM file too short for header", None, "header")

        # Check magic identifier
        if data[:4] not in OTBM_ACCEPTED_IDENTIFIERS:
            return ValidationResult(
                False,
                f"Invalid OTBM magic: got {data[:4]!r}",
                None,
                "header",
            )

        # Check root node type
        root_type = data[4]
        if root_type != 0xFE:
            return ValidationResult(
                False,
                f"Invalid root node marker: expected 0xFE, got 0x{root_type:02X}",
                root_type,
                "header",
            )

        return ValidationResult(True, "Valid OTBM header", root_type, "header")

    def _parse_root_node(self, data: bytes, offset: int) -> Tuple[int, Dict]:
        """Parse root node header."""
        if offset + 14 > len(data):
            raise ValueError("Root node header incomplete")

        # Parse root attributes
        version = struct.unpack_from("<I", data, offset)[0]
        width = struct.unpack_from("<H", data, offset + 4)[0]
        height = struct.unpack_from("<H", data, offset + 6)[0]
        item_major = struct.unpack_from("<I", data, offset + 8)[0]
        item_minor = struct.unpack_from("<I", data, offset + 12)[0]

        # Update statistics
        self.context.statistics.version = version
        self.context.statistics.width = width
        self.context.statistics.height = height
        self.context.statistics.item_version = f"{item_major}.{item_minor}"

        return offset + 16, {
            "version": version,
            "width": width,
            "height": height,
            "item_major": item_major,
            "item_minor": item_minor,
        }

    def _validate_full_structure(self, data: bytes, start_offset: int):
        """Validate the complete node structure."""
        self._validate_children(data, start_offset, len(data), OTBM_ROOTV1)

    def _validate_children(self, data: bytes, offset: int, end: int, parent_type: int):
        """Validate children recursively using each node's uint16 payload size."""
        while offset < end:
            if offset + 3 > end:
                self._add_issue(
                    "TRUNCATED_NODE",
                    f"Truncated node at offset {offset}",
                    SeverityLevel.CRITICAL,
                    context="structure",
                )
                return

            node_type, node_size, payload_offset = self._read_node_header(data, offset)
            next_offset = payload_offset + node_size
            if next_offset > end:
                self._add_issue(
                    "NODE_EXTENDS_BEYOND_FILE",
                    f"Node at offset {offset} extends beyond parent/file (size: {node_size})",
                    SeverityLevel.CRITICAL,
                    node_type=node_type,
                    context="structure",
                )
                return

            validation_result = self.node_rules.validate_hierarchy(parent_type, node_type)
            if not validation_result.passed:
                self._add_issue_from_result(validation_result)

            self._parse_node_content(data, payload_offset, node_type, node_size)
            self._update_statistics(node_type)

            child_start = self._child_payload_offset(data, payload_offset, next_offset, node_type)
            rule = self.node_rules.get_rule(node_type)
            if rule and rule.is_container and child_start < next_offset:
                self._validate_children(data, child_start, next_offset, node_type)

            offset = next_offset

    def _read_node_header(self, data: bytes, offset: int) -> Tuple[int, int, int]:
        """Read node header (type + size)."""
        node_type = data[offset]
        node_size = struct.unpack_from("<H", data, offset + 1)[0]
        return node_type, node_size, offset + 3

    def _validate_node_hierarchy(self, node_type: int, offset: int):
        """Validate node hierarchy against Canary rules."""
        if not self.context.node_stack:
            self._add_issue(
                "ORPHAN_NODE",
                f"Orphan node 0x{node_type:02X} at offset {offset}",
                SeverityLevel.CRITICAL,
                node_type=node_type,
                context="hierarchy",
            )
            return

        parent_type = self.context.node_stack[-1]
        validation_result = self.node_rules.validate_hierarchy(parent_type, node_type)

        if not validation_result.passed:
            self._add_issue_from_result(validation_result)

        # Push to stack if it's a container node
        rule = self.node_rules.get_rule(node_type)
        if rule and rule.is_container:
            self.context.node_stack.append(node_type)
        elif len(self.context.node_stack) > 1:
            # Pop from stack if we're leaving a container
            self.context.node_stack.pop()

    @staticmethod
    def _child_payload_offset(
        data: bytes, payload_offset: int, node_end: int, node_type: int
    ) -> int:
        """Return the first byte where child nodes begin for mixed-payload nodes."""
        offset = payload_offset
        if node_type == OTBM_MAP_DATA:
            for _ in range(3):
                if offset + 2 > node_end:
                    return node_end
                length = struct.unpack_from("<H", data, offset)[0]
                offset += 2 + length
            return min(offset, node_end)
        if node_type == OTBM_TILE_AREA:
            return min(offset + 5, node_end)
        if node_type == OTBM_SPAWN_AREA:
            return min(offset + 6, node_end)
        if node_type == OTBM_TILE:
            offset = min(offset + 2, node_end)
            if offset + 5 <= node_end and data[offset] == OTBM_ATTR_TILE_FLAGS:
                offset += 5
            return offset
        if node_type == OTBM_ITEM:
            return node_end
        return offset

    def _parse_node_content(self, data: bytes, offset: int, node_type: int, node_size: int):
        """Parse node content based on type."""
        # This would be implemented with detailed parsing logic
        # For now, we just validate the node exists and has reasonable size
        if node_size > 65535:
            self._add_issue(
                "NODE_TOO_LARGE",
                f"Node 0x{node_type:02X} size {node_size} exceeds maximum (65535)",
                SeverityLevel.ERROR,
                node_type=node_type,
                context="size_validation",
            )

    def _update_statistics(self, node_type: int):
        """Update validation statistics."""
        self.context.statistics.total_nodes += 1

        if node_type == OTBM_TILE:
            self.context.statistics.tiles += 1
        elif node_type == OTBM_ITEM:
            self.context.statistics.items += 1
        elif node_type == OTBM_SPAWN_AREA:
            self.context.statistics.spawn_areas += 1
        elif node_type == OTBM_MONSTER:
            self.context.statistics.monsters += 1
        elif node_type == OTBM_TOWN:
            self.context.statistics.towns += 1
        elif node_type == OTBM_WAYPOINT:
            self.context.statistics.waypoints += 1
        elif node_type == OTBM_HOUSETILE:
            self.context.statistics.house_tiles += 1

    def _add_issue(
        self,
        code: str,
        message: str,
        severity: SeverityLevel,
        node_type: Optional[int] = None,
        context: str = "",
    ):
        """Add a validation issue."""
        issue = ValidationIssue(
            code=code, message=message, severity=severity, node_type=node_type, context=context
        )
        self.context.issues.append(issue)

    def _add_issue_from_result(self, result: ValidationResult):
        """Add issue from validation result."""
        severity = SeverityLevel.ERROR
        if "critical" in result.message.lower() or "required" in result.message.lower():
            severity = SeverityLevel.CRITICAL
        elif "warning" in result.message.lower():
            severity = SeverityLevel.WARNING

        self._add_issue(
            code=f"HIERARCHY_{result.context.upper()}",
            message=result.message,
            severity=severity,
            node_type=result.node_type,
            context=result.context,
        )

    def _create_issue_from_result(
        self, result: ValidationResult, severity: SeverityLevel
    ) -> ValidationIssue:
        """Create validation issue from result."""
        return ValidationIssue(
            code=f"VALIDATION_{result.context.upper()}",
            message=result.message,
            severity=severity,
            node_type=result.node_type,
            context=result.context,
        )

    def _update_report_from_context(self, report: ValidationReport):
        """Update validation report from context."""
        # Copy statistics
        report.statistics = self.context.statistics

        # Copy issues
        for issue in self.context.issues:
            report.add_issue(issue)

        # Determine status
        if any(issue.severity == SeverityLevel.CRITICAL for issue in report.issues):
            report.status = ValidationStatus.FAILURE
        elif any(issue.severity == SeverityLevel.ERROR for issue in report.issues):
            report.status = ValidationStatus.FAILURE
        elif len(report.issues) > 0:
            report.status = ValidationStatus.WARNING
        else:
            report.status = ValidationStatus.SUCCESS

        # Set compatibility flags
        report.canary_compatible = report.status == ValidationStatus.SUCCESS
        report.rme_compatible = report.status == ValidationStatus.SUCCESS

    def validate_node_constants(self, data: bytes) -> ValidationReport:
        """Validate that the OTBM uses correct Canary node constants."""
        report = ValidationReport(ValidationStatus.UNKNOWN)
        report.file_path = "Node Constant Validation"

        # Check if file has Agente RME constants (0x00-based)
        # vs Canary constants (0x01-based)
        if len(data) < 5:
            report.add_issue(
                ValidationIssue(
                    code="FILE_TOO_SHORT",
                    message="File too short to determine node constants",
                    severity=SeverityLevel.CRITICAL,
                    context="node_constant_validation",
                )
            )
            report.status = ValidationStatus.FAILURE
            return report

        root_type = data[4]
        if root_type == AGENTE_OTBM_NODE_ROOT:
            report.add_issue(
                ValidationIssue(
                    code="AGENTE_NODE_CONSTANTS",
                    message=(
                        f"File uses Agente RME node constants (ROOT=0x{root_type:02X}) "
                        f"instead of Canary constants (ROOT=0x{OTBM_ROOTV1:02X})"
                    ),
                    severity=SeverityLevel.CRITICAL,
                    node_type=root_type,
                    context="node_constant_validation",
                    suggested_fix="Convert node constants from Agente to Canary format",
                )
            )
            report.status = ValidationStatus.FAILURE
        elif root_type == OTBM_ROOTV1:
            report.add_issue(
                ValidationIssue(
                    code="CANARY_NODE_CONSTANTS",
                    message=f"File uses correct Canary node constants (ROOT=0x{root_type:02X})",
                    severity=SeverityLevel.INFO,
                    node_type=root_type,
                    context="node_constant_validation",
                )
            )
            report.status = ValidationStatus.SUCCESS
        else:
            report.add_issue(
                ValidationIssue(
                    code="UNKNOWN_NODE_CONSTANTS",
                    message=f"File uses unknown node constant format (ROOT=0x{root_type:02X})",
                    severity=SeverityLevel.CRITICAL,
                    node_type=root_type,
                    context="node_constant_validation",
                )
            )
            report.status = ValidationStatus.FAILURE

        return report

    def validate_hierarchy_strict(self, data: bytes) -> ValidationReport:
        """Perform strict hierarchy validation."""
        report = ValidationReport(ValidationStatus.UNKNOWN)
        report.file_path = "Strict Hierarchy Validation"

        # This would implement detailed hierarchy validation
        # For now, return a placeholder
        report.add_issue(
            ValidationIssue(
                code="STRICT_VALIDATION_NOT_IMPLEMENTED",
                message="Strict hierarchy validation not yet implemented",
                severity=SeverityLevel.WARNING,
                context="hierarchy_validation",
            )
        )
        report.status = ValidationStatus.WARNING

        return report

    def validate_roundtrip_compatibility(
        self, original_data: bytes, reloaded_data: bytes
    ) -> ValidationReport:
        """Validate roundtrip compatibility (save → load → save)."""
        report = ValidationReport(ValidationStatus.UNKNOWN)
        report.file_path = "Roundtrip Compatibility Validation"

        if original_data == reloaded_data:
            report.add_issue(
                ValidationIssue(
                    code="ROUNDTRIP_SUCCESS",
                    message="Roundtrip validation successful - files are identical",
                    severity=SeverityLevel.INFO,
                    context="roundtrip_validation",
                )
            )
            report.status = ValidationStatus.SUCCESS
        else:
            report.add_issue(
                ValidationIssue(
                    code="ROUNDTRIP_MISMATCH",
                    message=(
                        "Roundtrip validation failed - files differ "
                        f"(original: {len(original_data)}, "
                        f"reloaded: {len(reloaded_data)} bytes)"
                    ),
                    severity=SeverityLevel.CRITICAL,
                    context="roundtrip_validation",
                )
            )
            report.status = ValidationStatus.FAILURE

        return report


__all__ = [
    "RMECompatibilityValidator",
    "RMEValidationContext",
]
