"""
Visual Map Critic AI — analyzes OpenTibia maps generated by Agente RME.

This package provides:
  * Models: CriticScore, CriticIssue, CriticRecommendation, CriticResult
  * Analyzers: navigation, density, spawn, hunt, boss_room, city, decor, region, pathfinding, visual
  * Engine: CriticEngine, ScoreCalculator, CriticReport, HeatmapRenderer
  * Entry point: VisualCritic
"""

from .critic_engine import CriticEngine
from .critic_report import CriticReport, CriticReportGenerator
from .score_calculator import ScoreCalculator
from .heatmap_renderer import HeatmapRenderer
from .visual_critic import VisualCritic
from .models import (
    CriticScore,
    CriticIssue,
    CriticRecommendation,
    CriticResult,
    CriticCategoryResult,
    IssueType,
    IssueSeverity,
    RecommendationPriority,
)

__all__ = [
    "VisualCritic",
    "CriticEngine",
    "CriticReport",
    "CriticReportGenerator",
    "ScoreCalculator",
    "HeatmapRenderer",
    "CriticScore",
    "CriticIssue",
    "CriticRecommendation",
    "CriticResult",
    "CriticCategoryResult",
    "IssueType",
    "IssueSeverity",
    "RecommendationPriority",
]
