"""
Lua Writer — responsible for writing Lua scripts for RME.

Supports two APIs:
1. Rich builder API (for programmatic generation):
     writer = LuaWriter()
     writer.header("Title")
     writer.transaction_begin()
     writer.set_ground(x, y, z, ground_id)
     writer.transaction_end()
     code = writer.to_string()

2. File writer API:
     writer = LuaWriter()
     writer.write("output/hunt.lua", lua_code)
"""

from __future__ import annotations

import os
from typing import List, Optional


class LuaWriter:
    """
    Writes Lua scripts for RME with a rich builder API.

    Usage (builder):
        writer = LuaWriter()
        writer.header("Test Zone")
        writer.transaction_begin()
        writer.set_ground(100, 100, 7, 415)
        writer.add_item(105, 105, 7, 1803)
        writer.set_spawn(110, 110, 7, "Sphinx", 60)
        writer.transaction_end()
        writer.end_statement()
        code = writer.to_string()

    Usage (file writer):
        writer = LuaWriter()
        writer.write("output/hunt.lua", lua_code)
    """

    def __init__(self):
        self._lines: List[str] = []

    # ------------------------------------------------------------------
    # Builder API
    # ------------------------------------------------------------------

    def clear(self):
        """Reset the internal buffer."""
        self._lines.clear()

    def header(self, title: str = "Generated by RME Agent"):
        """Write script header with guard."""
        self._lines.append(f'-- {title}')
        self._lines.append('')
        self._lines.append('if not app.hasMap() then')
        self._lines.append('    return')
        self._lines.append('end')
        self._lines.append('')
        self._lines.append('local map = app.map')
        self._lines.append('')

    def transaction_begin(self):
        """Open a transaction block."""
        self._lines.append('app.transaction(function(map)')
        self._lines.append('')

    def transaction_end(self):
        """Close a transaction block."""
        self._lines.append('end)')
        self._lines.append('')

    def end_statement(self):
        """Add final end statement (e.g., for camera position)."""
        pass  # Transaction already ends with end)

    def set_ground(self, x: int, y: int, z: int, ground_id: int):
        """Set ground tile at position."""
        self._lines.append(f'  local tile = map:getOrCreateTile({x}, {y}, {z})')
        self._lines.append(f'  tile.ground = {ground_id}')
        self._lines.append('')

    def add_item(self, x: int, y: int, z: int, item_id: int):
        """Add an item to a tile."""
        self._lines.append(f'  local tile = map:getOrCreateTile({x}, {y}, {z})')
        self._lines.append(f'  tile:addItem({item_id})')
        self._lines.append('')

    def set_spawn(self, x: int, y: int, z: int, monster_name: str, respawn: int, radius: int = 0):
        """Set a monster spawn on a tile."""
        self._lines.append(f'  local tile = map:getOrCreateTile({x}, {y}, {z})')
        self._lines.append(f'  tile:setSpawn({respawn})')
        self._lines.append(f'  tile:setCreature(\'{monster_name}\', {respawn}, Direction.SOUTH)')
        self._lines.append('')

    def write_ground_block(self, min_x: int, min_y: int, z: int, max_x: int, max_y: int, ground_id: int):
        """Write a block of ground tiles using nested for loops."""
        self._lines.append(f'  for x = {min_x}, {max_x} do')
        self._lines.append(f'    for y = {min_y}, {max_y} do')
        self._lines.append(f'      local tile = map:getOrCreateTile(x, y, {z})')
        self._lines.append(f'      tile.ground = {ground_id}')
        self._lines.append(f'    end')
        self._lines.append(f'  end')
        self._lines.append('')

    def comment(self, text: str):
        """Add a comment line."""
        self._lines.append(f'-- {text}')

    def raw(self, text: str):
        """Add raw text (no indentation)."""
        self._lines.append(text)

    def to_string(self) -> str:
        """Return the generated Lua code as a string."""
        return '\n'.join(self._lines)

    # ------------------------------------------------------------------
    # File writer API
    # ------------------------------------------------------------------

    def write(self, path: str, content: str) -> None:
        """
        Write Lua content to a file.

        Args:
            path: Output .lua file path.
            content: Lua content string.
        """
        directory = os.path.dirname(path)
        if directory:
            os.makedirs(directory, exist_ok=True)

        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)

    @staticmethod
    def write_string(content: str) -> str:
        """
        Returns content as-is (useful for testing).

        Args:
            content: Lua content.

        Returns:
            Same content unchanged.
        """
        return content
