"""
Lua Exporter — converts a WorldModel into a complete RME-compatible Lua script.

This is the key bridge between the generator system and the Lua/OTBM export
pipeline. It takes a populated WorldModel and produces optimized Lua code
using the RME DSL patterns.

Pipeline:
    WorldModel → LuaExporter → Lua script → LuaValidator → QA Pipeline

Architecture:
    The exporter groups tiles into contiguous blocks to minimize the
    number of Lua statements. Spawns are emitted individually.
"""

from __future__ import annotations

import logging
from typing import Any, Dict, List, Optional, Set, Tuple

from .lua_writer import LuaWriter
from .lua_validator import LuaValidator, LuaValidationResult
from core.world import WorldModel, Tile, Spawn, Region, Structure

logger = logging.getLogger(__name__)


class LuaExporter:
    """
    Converts a WorldModel to a complete RME Lua script.

    Usage:
        exporter = LuaExporter()

        # From WorldModel
        lua_code = exporter.export(world)

        # With title
        lua_code = exporter.export(world, title="Issavi Hunt Zone")

        # Export to file
        exporter.export_to_file(world, "output/hunt.lua")
    """

    DEFAULT_Z = 7

    def __init__(self):
        self._writer = LuaWriter()
        self._validator = LuaValidator()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def export(
        self,
        world: WorldModel,
        title: str = "",
    ) -> str:
        """
        Convert a WorldModel to a complete RME Lua script.

        Args:
            world: Populated WorldModel to export.
            title: Optional title for the script header.

        Returns:
            Complete Lua script as a string.
        """
        self._writer.clear()

        # 1. Header with guard
        self._writer.header(title or "Generated by RME Agent")

        # 2. Open transaction block
        self._writer.transaction_begin()

        # 3. Export structures (blueprint placements)
        self._export_structures(world)

        # 4. Export individual tiles (ground + items)
        self._export_tiles(world)

        # 5. Export spawns
        self._export_spawns(world)

        # 6. Close transaction block
        self._writer.transaction_end()

        # 7. Add camera position
        self._writer.end_statement()

        return self._writer.to_string()

    def export_to_file(
        self,
        world: WorldModel,
        filepath: str,
        title: str = "",
    ) -> None:
        """
        Export WorldModel to a Lua file.

        Args:
            world: Populated WorldModel to export.
            filepath: Path for the output .lua file.
            title: Optional title.
        """
        lua_code = self.export(world, title=title)
        import os
        os.makedirs(os.path.dirname(filepath) or ".", exist_ok=True)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(lua_code)
        logger.info(f"Exported Lua to {filepath}")

    def validate(self, world: WorldModel) -> LuaValidationResult:
        """
        Export and validate in one step.

        Args:
            world: WorldModel to validate.

        Returns:
            LuaValidationResult.
        """
        lua_code = self.export(world)
        return self._validator.validate(lua_code)

    # ------------------------------------------------------------------
    # Internal export methods
    # ------------------------------------------------------------------

    def _export_structures(self, world: WorldModel) -> None:
        """Export structures as comments for documentation."""
        for structure in world.structures:
            self._writer.comment(
                f"Structure: {structure.name} "
                f"({structure.category}) "
                f"at ({structure.x},{structure.y},z={structure.z}) "
                f"size {structure.width}x{structure.height}"
            )

        # Export regions as comments
        for region in world.regions:
            self._writer.comment(
                f"Region: {region.name} "
                f"(theme={region.theme}, "
                f"levels={region.min_level}-{region.max_level})"
            )

        if world.structures or world.regions:
            self._writer.raw("")  # blank line

    def _export_tiles(self, world: WorldModel) -> None:
        """Export all tiles to Lua."""
        if not world.tiles:
            logger.warning("No tiles to export")
            return

        tiles = list(world.tiles.values())

        # Group tiles by z-level first
        tiles_by_z: Dict[int, List[Tile]] = {}
        for tile in tiles:
            tiles_by_z.setdefault(tile.z, []).append(tile)

        for z in sorted(tiles_by_z.keys()):
            z_tiles = tiles_by_z[z]
            self._writer.comment(f"Layer z={z} ({len(z_tiles)} tiles)")

            # Find contiguous ground blocks
            ground_tiles = [t for t in z_tiles if t.ground is not None]
            if ground_tiles:
                self._export_ground_grouped(ground_tiles, z)

            # Export items (decorations, etc.)
            item_tiles = [t for t in z_tiles if t.items]
            if item_tiles:
                self._export_items(item_tiles, z)

    def _export_ground_grouped(self, tiles: List[Tile], z: int) -> None:
        """
        Export ground tiles grouped by ground_id for efficiency.

        Instead of one Lua statement per tile, this generates nested
        for loops for each contiguous block of tiles with the same ground_id.
        """
        # Group tiles by ground ID
        by_ground: Dict[int, List[Tile]] = {}
        for t in tiles:
            gid = t.ground
            if gid is not None:
                by_ground.setdefault(gid, []).append(t)

        for ground_id, g_tiles in sorted(by_ground.items()):
            if len(g_tiles) > 16:
                # For large groups, find bounds and write a single block
                min_x = min(t.x for t in g_tiles)
                max_x = max(t.x for t in g_tiles)
                min_y = min(t.y for t in g_tiles)
                max_y = max(t.y for t in g_tiles)

                # Estimate tile count vs bounding box area
                area = (max_x - min_x + 1) * (max_y - min_y + 1)
                fill_ratio = len(g_tiles) / area

                if fill_ratio > 0.8:
                    # Dense block: use a for loop
                    self._writer.write_ground_block(
                        min_x, min_y, z, max_x, max_y, ground_id
                    )
                    continue

            # Fallback: individual tiles
            for t in g_tiles:
                self._writer.set_ground(t.x, t.y, z, t.ground)

    def _export_items(self, tiles: List[Tile], z: int) -> None:
        """Export items (decorations) on tiles."""
        for tile in tiles:
            for item in tile.items:
                item_id = None
                if isinstance(item, dict):
                    item_id = item.get("id") or item.get("itemid")
                elif hasattr(item, "itemid"):
                    item_id = item.itemid
                elif hasattr(item, "id"):
                    item_id = item.id

                if item_id is not None:
                    self._writer.add_item(tile.x, tile.y, z, int(item_id))

    def _export_spawns(self, world: WorldModel) -> None:
        """Export monster spawns."""
        # Collect all spawns from tiles
        spawns: List[Tuple[int, int, int, Spawn]] = []
        for tile in world.tiles.values():
            if tile.spawn is not None:
                spawns.append((tile.x, tile.y, tile.z, tile.spawn))

        if not spawns:
            return

        self._writer.raw("")
        self._writer.comment(f"Spawns ({len(spawns)} entries)")

        for x, y, z, spawn in spawns:
            self._writer.set_spawn(
                x, y, z,
                monster_name=spawn.monster,
                respawn=spawn.respawn,
                radius=spawn.radius,
            )